# 필드 정의
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
HEAD_ENTITY_ID_FIELD: head_id
TAIL_ENTITY_ID_FIELD: tail_id
RELATION_ID_FIELD: relation_id
ENTITY_ID_FIELD: entity_id

# 데이터 불러오기
load_col:
    inter: [user_id, item_id]
    kg: [head_id, relation_id, tail_id]
    link: [item_id, entity_id]

# 평가 설정
eval_args:
    split: {'RS': [0.8, 0.1, 0.1]}
    order: RO
    mode: full
    group_by: user

metrics: ['Recall', 'NDCG', 'Hit', 'Precision']
topk: 10
valid_metric: Recall@10

# KGCN 하이퍼파라미터
embedding_size: 64
learning_rate: 0.002
reg_weight: 1e-5
neighbor_sample_size: 8
n_iter: 1
aggregator: sum
stopping_step: 10